class Lot < Formula
  include Language::Python::Virtualenv

  desc "Manage git-backed lists of anything from the command-line"
  homepage "https://github.com/logaan/lot.rs"
  version "0.1.2"
  license "MIT"

  # Build the latest from main (requires a Rust toolchain) with `--HEAD`.
  # Head builds get only the `lot` binary, not the Python UI.
  head do
    url "https://github.com/logaan/lot.rs.git", branch: "main"
    depends_on "rust" => :build
  end

  # For the Python Textual UI (`lot interface` / `lot web`).
  depends_on "python@3.13"

  # Prebuilt binaries from the GitHub Release -- no Rust toolchain is pulled in.
  # This file is generated by scripts/update-tap in the lot.rs repo; regenerate
  # it there rather than editing by hand.
  on_macos do
    on_arm do
      url "https://github.com/logaan/lot.rs/releases/download/v0.1.2/lot-v0.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "7cbf98ccc7722f953e61bfa37043979fb543ebd80456ad37efe0ae5514822fc1"
    end
    on_intel do
      url "https://github.com/logaan/lot.rs/releases/download/v0.1.2/lot-v0.1.2-x86_64-apple-darwin.tar.gz"
      sha256 "cbbc32b414ab0fe8e30f25e21a5e64b0263cc6b61d8a9ef547c6a3c4a9bd84aa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/logaan/lot.rs/releases/download/v0.1.2/lot-v0.1.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6067a439c166ef89b5c98c4e45e0cd906047f3c0c167436a6278ec41b0354489"
    end
    on_intel do
      url "https://github.com/logaan/lot.rs/releases/download/v0.1.2/lot-v0.1.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fef98c9a1ce3288ac2ad795202741ae6441afcb4111811a49926b8a62c704694"
    end
  end

  # The Python Textual UI (`lot interface` / `lot web` launch its
  # `lot-textual-ui` / `lot-textual-ui-web` binaries from next to `lot`).
  resource "lot-textual-ui" do
    url "https://github.com/logaan/lot.rs/releases/download/v0.1.2/lot_textual_ui-0.1.2.tar.gz"
    sha256 "c2d53f0dec089e984f4e379a6e6405a02e39e0be32d7766502d72928e242e87b"
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args(path: "crates/lot-cli")
      return
    end

    bin.install "lot"

    # Install the Textual UI into a venv under libexec and put its launchers
    # next to `lot` in bin, which is where `lot interface`/`lot web` look
    # first. Unlike the usual venv.pip_install (which passes --no-deps), this
    # lets pip pull the dependencies (textual, PyYAML, textual-serve) from
    # PyPI at install time -- acceptable for a personal tap.
    virtualenv_create(libexec, "python3.13")
    resource("lot-textual-ui").stage do
      system "python3.13", "-m", "pip", "--python=#{libexec}/bin/python",
             "install", "."
    end
    bin.install_symlink libexec/"bin/lot-textual-ui", libexec/"bin/lot-textual-ui-web"
  end

  test do
    assert_match(/^lot \d+\.\d+\.\d+/, shell_output("#{bin}/lot --version"))

    ENV["GIT_AUTHOR_NAME"] = ENV["GIT_COMMITTER_NAME"] = "brew test"
    ENV["GIT_AUTHOR_EMAIL"] = ENV["GIT_COMMITTER_EMAIL"] = "test@brew.sh"
    system bin/"lot", "vault", "new", testpath/"vault"
    assert_path_exists testpath/"vault/readme.md"

    # The Python UI launchers ship with the prebuilt install (not --HEAD).
    unless build.head?
      assert_path_exists bin/"lot-textual-ui"
      assert_path_exists bin/"lot-textual-ui-web"
    end
  end
end
